name: OS run

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qemu
      run: |
        sudo apt-get update
        sudo apt-get install qemu qemu-kvm
    - name: Install Nasm
      run: sudo apt-get install nasm
    
    - name: Install GCC
      run: sudo apt-get install gcc
      
    - name: Install make
      run: sudo apt-get install make
    
    - name: Build
      run: make
