name: OS run

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qemu
      run: |
        git clone --recurse-submodules -j8 https://github.com/qemu/qemu.git
        cd qemu
        mkdir build
        cd build
        ../configure
        make
      
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
